# <1>
5.1번 mlbench 패키지의 BreastCancer 자료에 대하여 적절한 크기의 나무모형을 적합하라.
```{r} 
library(mlbench)
library(tree)
data("BreastCancer")
sum(is.na(BreastCancer)) #NA값이 있기에 생략해보자.
bc <- na.omit(BreastCancer[,-1])
bc[1:9] <- apply(bc[1:9],2,as.numeric)
str(bc)
bc.tr <- tree(Class~.,data = bc)
plot(bc.tr) ; text(bc.tr, all = T)
bc.tr 

bc.tr2 <- prune.misclass(bc.tr)
plot(bc.tr2) # 6부터 아예 차이가 없어짐.
fin_bc.tr <- prune.misclass(bc.tr, best=6)
plot(fin_bc.tr) ; text(fin_bc.tr, all = T)
# prune.misclass함수의 교차확인 오분류율을 이용하여 k가 최소가 되는 끝마디를 선택하여(현재 경우 6) 가지치기한 결과의 나무모형은 다음과 같다.
```
# <2>
5.3번 mlbench 패키지의 HouseVotes84자료에 대해 party 패키지의 함수로 나무모형 적합하고 결과를 해석하라.
```{r}
data("HouseVotes84")
sum(is.na(HouseVotes84)) # 데이터를 보았을 때, 기권표(NA)가 너무많아 생략하기 보단 기권이라는 새로운 level  주는 것이 더 좋아보임.
hv <- HouseVotes84[,-1]
str(hv)
for (i in 1:length(hv)){
  hv[,i] <- as.character(hv[,i])
  hv[,i][is.na(hv[,i])] <- 'abstain'
  hv[,i] <- as.factor(hv[,i])
}
str(hv)
hv <- cbind(Class=HouseVotes84$Class,hv)

library(party)
hv_ctree <- ctree(Class~.,data=hv)
print(hv_ctree)
plot(hv_ctree, type='simple')
# 몇가지 예시를 통해 해석을 하자면, V4의 법안에서 기권 또는 반대를 한 쪽 중에서 V3를 를 기권한 쪽은 민주당과 공화당을 (0.67:0.33)으로 분류한다. 그리고 V4를 찬성한사람중 V11을 반대또는기권하고, 그 중 V15를 반대또는 기권한 사람은 민주당과 공화당을 (0.008:0.992)로 분류한다.
```
# <3>
CDC 2010 데이터에 대하여 atRisk가 출력변수인 의사결정 나무모형을 적합하고 결과를 해석하시오.
```{r}
#3. CDC 2010 데이터에 대하여 atRisk가 출력변수인 의사결정 나무모형을 적합하고 결과를 해석하시오
load("C:/Users/kyucheol/Desktop/학교생활/과제/4학년 1학기/데이터마이닝/NatalRiskData.rData")
sum(is.na(sdata)) #결측치가 존재하지 않는다.
str(sdata)
for (i in c(3,6:13)){
  sdata[,i] <- as.factor(sdata[,i])
} #logi변수들을 Factor로 바꾸었다.
library(party)
cdc_ctree <- ctree(atRisk~.,data=sdata)
print(cdc_ctree)
plot(cdc_ctree,type='simple')
# 우선 DBWT가 1350보다 작고, 또한 538보다 작으면 (0.03:0.97)로 atRisk를 FALSE:TRUE 로 분류한다. 또한 DBWT가 1350보다 크고 GESTREC3이 37주 이상이며 ULD_MECO가 FALSE일때는 atRisk를 FALSE:TRUE를 (0.989:0.011)로 분류한다.
```